version: 0.2
phases:
  install:
    commands:
      - apt update -y
      - apt install zip -y
      - apt install python3 python3-pip -y
  build:
    commands:
      - ./buildinvoker.sh
artifacts:
  files:
    - deployment/*
    - invoker.zip